#ifndef _URTC_URTCELECDEFINE_H_
#define _URTC_URTCELECDEFINE_H_

typedef void(*ELECAVSDKCALLBACK)(int eventid, const char* data);
typedef void(*ELECAUDIOCALLBACK)(int eny);

typedef enum _tUrtcElecEventid {
	URTC_ELEC_EVENT_OK = 5000,
	URTC_ELEC_EVENT_SERVER_DIS ,
	URTC_ELEC_EVENT_JOINROOM,
	URTC_ELEC_EVENT_LEAVEROOM,
	URTC_ELEC_EVENT_RECONNECTING,
	URTC_ELEC_EVENT_RECONNECT,
	URTC_ELEC_EVENT_PUBLISH,
	URTC_ELEC_EVENT_UNPUBLISH,
	URTC_ELEC_EVENT_USER_JOIN,
	URTC_ELEC_EVENT_USER_LEAVE,
	URTC_ELEC_EVENT_REMOTE_PUBLISH,
	URTC_ELEC_EVENT_REMOTE_UNPUBLISH,
	URTC_ELEC_EVENT_SUB_RESULT,
	URTC_ELEC_EVENT_UNSUB_RESULT,
	URTC_ELEC_EVENT_LOCAL_MEDIA_MUTE,
	URTC_ELEC_EVENT_REMOTE_MEDIA_MUTE,
	URTC_ELEC_EVENT_STREAM_ST_NOTIFY,
	URTC_ELEC_EVENT_LOCAL_AUDIO_LEVEL,
	URTC_ELEC_EVENT_REMOTE_AUDIO_LEVEL,
	URTC_ELEC_EVENT_STARTRECORD,
	URTC_ELEC_EVENT_STOPRECORD
}tUrtcElecEventid;

#endif

