#ifndef _UCLOUD_RTC_ERROR_CODE_H_
#define _UCLOUD_RTC_ERROR_CODE_H_

typedef enum _tUCloudRtcCallbackErrCode {
	UCLOUD_RTC_CALLBACK_ERR_CODE_OK = 0,
	UCLOUD_RTC_CALLBACK_ERR_SERVER_CON_FAIL = 5000, //服务器连接失败
	UCLOUD_RTC_CALLBACK_ERR_SERVER_DIS, // 服务端连接断开
	UCLOUD_RTC_CALLBACK_ERR_SAME_CMD,  //重复的调用
	UCLOUD_RTC_CALLBACK_ERR_NOT_IN_ROOM, //未加入房间 无发进行操作 
	UCLOUD_RTC_CALLBACK_ERR_ROOM_JOINED, // 已加入房间 无需加入
	UCLOUD_RTC_CALLBACK_ERR_SDK_INNER,   // SDK 内部错误
	UCLOUD_RTC_CALLBACK_ERR_ROOM_RECONNECTING, // 重连中 请求无法投递      
	UCLOUD_RTC_CALLBACK_ERR_STREAM_PUBED,  // 流已经发布  无需发布
	UCLOUD_RTC_CALLBACK_ERR_STREAM_NOT_PUB, //流没有发布 无法对流进行操作
	UCLOUD_RTC_CALLBACK_ERR_STREAM_SUBED,  //流已经订阅  无需订阅
	UCLOUD_RTC_CALLBACK_ERR_STREAM_NO_SUB, //流没有订阅  无法
	UCLOUD_RTC_CALLBACK_ERR_SUB_NO_USER,   //无对应的用户 无法订阅
	UCLOUD_RTC_CALLBACK_ERR_SUB_NO_STREAM,  // 无对应的媒体流
	UCLOUD_RTC_CALLBACK_ERR_USER_LEAVING, // 用户正在离开房间  无法进行其他操作
	UCLOUD_RTC_CALLBACK_ERR_NO_HAS_TRACK,  //无对应的媒体轨道
	UCLOUD_RTC_CALLBACK_ERR_MSG_TIMEOUT, // 消息请求超时
}tUCloudRtcCallbackErrCode;

typedef enum _tUCloudRtcReturnErrCode {
	UCLOUD_RTC_RETURN_ERR_CODE_OK = 0,
	UCLOUD_RTC_RETURN_ERR_AUTO_PUB = 1000, //自动发布
	UCLOUD_RTC_RETURN_ERR_AUTO_SUB, //自动订阅
	UCLOUD_RTC_RETURN_ERR_NOT_INIT, //引擎没有初始化
	UCLOUD_RTC_RETURN_ERR_IN_ROOM, //已经加入房间
	UCLOUD_RTC_RETURN_ERR_NOT_IN_ROOM, // 未加入房间
	UCLOUD_RTC_RETURN_ERR_NOT_PUB_TRACK, //未发布对应媒体
	UCLOUD_RTC_RETURN_ERR_INVAILED_PARGRAM,// 无效参数
	UCLOUD_RTC_RETURN_ERR_INVAILED_WND_HANDLE,// 无效窗口句柄
	UCLOUD_RTC_RETURN_ERR_INVAILED_MEDIA_TYPE,// 无效媒体类型
	UCLOUD_RTC_RETURN_ERR_SUB_ONEMORE,// 最少订阅一种媒体
	UCLOUD_RTC_RETURN_ERR_NO_PUB_ROLE, //无发布权限
	UCLOUD_RTC_RETURN_ERR_NO_SUB_ROLE, //无订阅权限
	UCLOUD_RTC_RETURN_ERR_CAM_NOT_ENABLE, //没有配置本地cam 发送
	UCLOUD_RTC_RETURN_ERR_SCREEN_NOT_ENABLE, //没有配置本地screen 发送
	UCLOUD_RTC_RETURN_ERR_AUDIO_MODE,        // 纯音频模式
	UCLOUD_RTC_RETURN_ERR_SECKEY_INVALID ,    // seckey 无效
	UCLOUD_RTC_RETURN_ERR_INVAILD_FILEPATH,
	UCLOUD_RTC_RETURN_ERR_NOT_SUPORT_AUDIO_FORMAT,
}tUCloudRtcReturnErrCode;

#endif

