#ifndef _UCLOUD_RTC_ERROR_CODE_H_
#define _UCLOUD_RTC_ERROR_CODE_H_

typedef enum _tUCloudRtcCallbackErrCode{
	UCLOUD_RTC_CALLBACK_ERR_CODE_OK=0, 
	UCLOUD_RTC_CALLBACK_ERR_SAME_CMD = 3000, 
	UCLOUD_RTC_CALLBACK_ERR_NOT_IN_ROOM, 
	UCLOUD_RTC_CALLBACK_ERR_ROOM_JOINED, 
	UCLOUD_RTC_CALLBACK_ERR_NETWORK,
	UCLOUD_RTC_CALLBACK_ERR_ROOM_RECONNECTING,
	UCLOUD_RTC_CALLBACK_ERR_PUB_TOO_MORE,
	UCLOUD_RTC_CALLBACK_ERR_STREAM_PUBED, 
	UCLOUD_RTC_CALLBACK_ERR_STREAM_NOT_PUB,
	UCLOUD_RTC_CALLBACK_ERR_STREAM_SUBED, 
	UCLOUD_RTC_CALLBACK_ERR_STREAM_NO_SUB,
	UCLOUD_RTC_CALLBACK_ERR_SUB_NO_USER,
	UCLOUD_RTC_CALLBACK_ERR_SUB_NO_MEDIA,
	UCLOUD_RTC_CALLBACK_ERR_USER_LEAVING, 
	UCLOUD_RTC_CALLBACK_ERR_SERVER_CON_FAIL, 
	UCLOUD_RTC_CALLBACK_ERR_INVAILD_ST,
	UCLOUD_RTC_CALLBACK_ERR_SERVER_DIS,   
	UCLOUD_RTC_CALLBACK_ERR_NO_HAS_TRACK,
	UCLOUD_RTC_CALLBACK_ERR_MSG_TIMEOUT,
}tUCloudRtcCallbackErrCode;

typedef enum _tUCloudRtcReturnErrCode {
	UCLOUD_RTC_RETURN_ERR_CODE_OK = 0,
	UCLOUD_RTC_RETURN_ERR_AUTO_PUB = 1000, //自动发布
	UCLOUD_RTC_RETURN_ERR_AUTO_SUB, //自动订阅
	UCLOUD_RTC_RETURN_ERR_NOT_INIT, //引擎没有初始化
	UCLOUD_RTC_RETURN_ERR_IN_ROOM, 
	UCLOUD_RTC_RETURN_ERR_NOT_IN_ROOM,
	UCLOUD_RTC_RETURN_ERR_NOT_PUB_TRACK, 
	UCLOUD_RTC_RETURN_ERR_INVAILED_PARGRAM,// 无效参数
	UCLOUD_RTC_RETURN_ERR_INVAILED_WND_HANDLE,// 无效窗口句柄
	UCLOUD_RTC_RETURN_ERR_INVAILED_MEDIA_TYPE,// 无效媒体类型
	UCLOUD_RTC_RETURN_ERR_SUB_ONEMORE,// 最少订阅一种媒体
	UCLOUD_RTC_RETURN_ERR_NO_PUB_ROLE, //无发布权限
	UCLOUD_RTC_RETURN_ERR_NO_SUB_ROLE, //无订阅权限
	UCLOUD_RTC_RETURN_ERR_CAM_NOT_ENABLE, //没有配置本地cam 发送
	UCLOUD_RTC_RETURN_ERR_SCREEN_NOT_ENABLE, //没有配置本地screen 发送
	UCLOUD_RTC_RETURN_ERR_AUDIO_MODE,
	UCLOUD_RTC_RETURN_ERR_SECKEY_INVALID
}tUCloudRtcReturnErrCode;

#endif

